# Generated by Django 5.2 on 2025-06-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trash", "0003_devicetoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[("푸시", "푸시"), ("민원", "민원")], max_length=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_sent", models.BooleanField(default=False)),
            ],
        ),
    ]
